language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t monicabanasure-react -f Dockerfile.dev .

script:
  - docker run -e CI=true monicabanasure/docker-react npm run test

